# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        documents:
            persistence:
                driver: orm
                model: App\Entity\DocumentContent
            properties:
                content: { boost: 6, type: text }
                document: 
                    type: "nested"
                    properties: 
                        id: { type: integer }
                        title: { boost: 2, type: text }
                        description: { boost: 4, type: text }
                category: 
                    type: "nested"
                    properties:
                        id: {type: integer, boost: 10 }
                        title: {boost: 2, type: text}
                tag: 
                    type: "nested"
                    properties:
                        id: {type: integer, boost: 10 }
                        title: {boost: 2, type: text}

