version: '3.4'
services:
  sistema_editoriale_elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: sistema_editoriale_elastic_search
    environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 512mo HEAP
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - sistema_editoriale_elastic_search:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - sistema_editoriale_elastic_search_network
      - sistema_documentale_backend_network
    restart: always

  # sistema_editoriale_kibana:
  #   container_name: sistema_editoriale_kibana
  #   image: docker.elastic.co/kibana/kibana:7.9.3
  #   restart: always
  #   volumes:
  #     - ./kibana/config.yml:/usr/share/kibana/config/kibana.yml
  #   depends_on:
  #       - sistema_editoriale_elastic_search
  #   ports:
  #       - 5601:5601
  #   networks:
  #     - sistema_editoriale_elastic_search_network

volumes:
  sistema_editoriale_elastic_search:
    driver: local

networks:
  sistema_editoriale_elastic_search_network:
    driver: bridge
  sistema_documentale_backend_network:
    driver: bridge